### ISSUE TITLE
missing svg in the nav bar in smaller screens

### ISSUE THREAD

**Issue by sridamul** [jenkins-infra/docs.jenkins.io#40]
### Reproduction steps

Navigate to [docs site](https://docs.jenkins.io/user-docs/2.426.x/index.html) and view it in smaller screen

### Expected Results

![with_icon](https://github.com/jenkins-infra/docs.jenkins.io/assets/107404972/1c85315f-73a7-48a5-a66f-5e87cd9cff9c)

### Actual Results

![mobile view](https://github.com/jenkins-infra/docs.jenkins.io/assets/107404972/43ecbe63-f63f-4dcc-8572-80816e04cab7)

### Anything else?

also it would be better to add padding to the sides of the content when viewed on the smaller screen size (especially mobile screen)

**Comment by Vandit1604** [comment]
#42 Adds padding around the content on smaller screens.

**Comment by suzitsam** [comment]
I would like to work on this.

**Comment by Vandit1604** [comment]
@suzitsam Go ahead and submit the pull request for this fix.

**Comment by Ravijhabit** [comment]
Hi @krisstern, Can this issue be assigned to me after 3 days if there is no progress from @suzitsam ?

**Comment by krisstern** [comment]
Hi @Ravijhabit I don't think that is a good idea! It would be hard for us maintainers to keep track of such queues. You will have to check back in about 2 days time to see if Suzit has submitted a PR yet. If not it is for anyone to take on a first-come-first-serve basis starting from then.

**Comment by Ravijhabit** [comment]
Got it @krisstern, 
I would be constantly looking into the progress of this issue.
Thank you

**Comment by Coffemin** [comment]
@krisstern Seems like it's been a week since suzitsam said he will work on this issue but still PR, Can I work on this issue?

**Comment by krisstern** [comment]
Hi @Coffemin Sure, you may work on this!

**Comment by Ravijhabit** [comment]
Hi @krisstern,
This repo has 7 day waiting policy and FCFS after issue is assigned to someone. Am I incorrect on this ?
I was waiting for completion of 7th day (7th day completes today).
This was demotivating for me.

**Comment by krisstern** [comment]
Hey @Ravijhabit,

Thanks for your interest in contributing to Jenkins! Actually when @Coffemin asked about whether he could work on the issue we did check that the 7th day had been reached (or a week had passed). But you are welcome to contribute to the other issues in the issue tracker for Hacktoberfest 2024. This is because the repo already has the `hacktoberfest` label so any PR accepted will be tracked. I am going to create more "good first issues" within the next 24 hours so feel free to express your interest and contribute to those as well.

**Comment by Coffemin** [comment]
Hi @krisstern, I’ve been working on adding an SVG icon to the navbar burger button but can’t seem to figure it out.

I’ve tried the following in ui/src/css/header.css:

.navbar-burger {
  background: url(../img/3-line-menu.svg) no-repeat 50% 47.5%;
  background-size: 49%;
  border: none;
  outline: none;
  line-height: inherit;
  padding: 0;
  height: var(--toolbar-height);
  width: var(--toolbar-height);
  margin-right: -0.25rem;
}

I have the 3-line-menu.svg file located in the img folder, but it still doesn’t display. I’ve checked if other classes might be blocking the display but can’t seem to identify the issue.

Any help or guidance would be greatly appreciated!

**Comment by krisstern** [comment]
Hi @Coffemin,

I think this may be due to some configuration of the missing `ionicon` class. You may take a look at how this can be fixed but in the Gatsby framework instead of the Antora framework at https://github.com/jenkins-infra/contributor-spotlight/blob/d47dcd8c37d54115a03d96f77cba5c27f98e2e34/gatsby-ssr.jsx#L16 between L16 and L25 for some inspiration of a fix.
