### ISSUE TITLE
Images on projects/blueocean/about.html are overlapping the TOC

### ISSUE THREAD

**Issue by Vandit1604** [jenkins-infra/docs.jenkins.io#61]
### Describe your use-case which is not covered by existing documentation.

Concerned page: https://docs.jenkins.io/projects/blueocean/about.html

Images on the concerned page are taking full width and overlapping the TOC. 

![image](https://github.com/jenkins-infra/docs.jenkins.io/assets/107131545/b72ec0c8-1b59-4889-b813-0976ca08e214)

**Comment by Allan2000-Git** [comment]
@Vandit1604 @krisstern I'd love to work on this issue

**Comment by krisstern** [comment]
Hi @sarthak-kumar-shailendra It looks like something else is working on the issue based on the commit history but they had not made any progress since 5 days ago. Also we have a policy to wait for 7 days before another contributor can take over, so depends on whether I will here back from @Allan2000-Git I may need to close your PR later.
